name: Czechibank Registration Test
on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        
      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
      - name: Install Newman
        run: npm install -g newman

      - name: Install pg
        run: npm install pg
        
      - name: Run Postman Collection
        run: newman run new_user_registration.postman_collection.json --environment Czechibank.postman_environment.json 

      
    


