name: Czechibank Registration Test
on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        
      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
      - name: Install Newman
        run: npm install -g newman

      - name: Install pg
        run: npm install pg
        
      - name: Run Postman Collection
        run: newman run new_user_registration.postman_collection.json --environment Czechibank.postman_environment.json --export-environment exported_env.json
      - name: Export email to GitHub ENV
        run: |
          EMAIL=$(node -e "
            const env = require('./exported_env.json');
            const emailVar = env.values.find(v => v.key === 'email');
            console.log(emailVar.value);
          ")
          echo "REGISTERED_EMAIL=$EMAIL" >> $GITHUB_ENV

      - name: Verify user in DB
        run: |
          node -e "
            const { Client } = require('pg');
            const client = new Client({
              connectionString: process.env.DB_CONNECTION_STRING
            });

            async function verifyUser() {
              try {
                await client.connect();
                console.log('DB připojení úspěšné');
              } catch (err) {
                console.error('CHYBA při připojení:', err.message);
                process.exit(1);
              } finally {
                await client.end();
              }
            }

            verifyUser();
          "
    


